### ISSUE TITLE
Workflow for Approving Users

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-enviro#197]
The workflow is as follows:
- [x] The user fills out the request access for on the app
- [x] An email gets sent to the admin with a link to the user admin page (approving users directly from a link in the email will not work since the admin will need to set the geographic extent manually) ([related permission proxy issue](https://github.com/agrc/ArcGisServerPermissionsProxy/issues/62))
- [x] The admin goes to the user admin page and sets the geographic extent and verifies the expiration date using the form described in #196.
- [x] Then the admin could approve the user directly from the user admin page
- [x] The user gets a confirmation email that includes the geographic extents and expiration date. ([related permission proxy issue](https://github.com/agrc/ArcGisServerPermissionsProxy/issues/62))
